export const filtros = {
  operador: [
    {
      id: 1,
      name: 'Jose Peres',
    },
    {
      id: 2,
      name: 'Diego Paes',
    },
    {
      id: 3,
      name: 'Maxi Gomez',
    },
    {
      id: 4,
      name: 'Ivan Gutierres',
    },
  ],
  priority: [
    {
      id: 1,
      name: 'Hight',
    },
    {
      id: 2,
      name: 'Regular',
    },
    {
      id: 3,
      name: 'Medium',
    },
  ],
  qcStatus: [
    {
      id: 1,
      name: 'Rejected',
    },
    {
      id: 2,
      name: 'Process',
    },
    {
      id: 3,
      name: 'QcOk',
    },
  ],
  distributor: [
    {
      id: 1,
      name: 'ESPN',
    },
    {
      id: 1,
      name: 'FOX',
    },
  ],
};

export const menu = {
  id: 1,
  name: 'Menu',
  data: [
    {
      id: 1,
      name: 'Home',
      data: [],
      api: null,
    },
    {
      id: 2,
      name: 'Tasks',
      data: [
        {
          id: 7,
          name: 'Ingest',
          data: [],
          api: 'api/ingest',
        },
        {
          id: 8,
          name: 'Version',
          data: [],
          api: null,
        },
        {
          id: 9,
          name: 'Append',
          data: [],
          api: null,
        },
        {
          id: 10,
          name: 'M.Location',
          data: [],
          api: null,
        },
        {
          id: 11,
          name: 'Record',
          data: [],
          api: null,
        },
      ],
      api: null,
    },
    {
      id: 3,
      name: 'Libreri',
      data: [],
      api: null,
    },
    {
      id: 4,
      name: 'Tranfers',
      data: [],
      api: null,
    },
    {
      id: 5,
      name: 'Reports',
      data: [],
      api: null,
    },
    {
      id: 6,
      name: 'Admin',
      data: [],
      api: null,
    },
  ],
};

export const user = {
  id: 1,
  name: ' Lucas Gonzales',
  permissions: [
    {
      id: 1,
      name: 'Menu',
    },
    {
      id: 2,
      name: 'Home',
    },
    {
      id: 3,
      name: 'Tasks',
    },
    {
      id: 8,
      name: 'Ingest',
    },
    {
      id: 6,
      name: 'Reports',
    },
  ],
};

export const tableData = [
  {
    showCode: 'ARFI01154',
    title: 'FI -GP EEUU',
    priorityId: 1,
    priorityName: 'High',
    placeH: '01/10/2022',
    readyQc: '',
    readyQcValue: false,
    qcOk: '',
    qcOkId: 2,
    dalet: '',
    typeId: 3,
    typeName: 'Long F.',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 178,
    logDate: '05/10/2022',
    operadorName: 'Jose',
    operadorId: 1,
  },
  {
    showCode: 'P123456',
    title: 'PROMO-XXXX',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '01/10/2022',
    readyQc: '02/10/2022',
    readyQcValue: true,
    qcOk: 'Rejected',
    qcOkId: 1,
    dalet: '',
    typeId: 2,
    typeName: 'PROMO',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 14,
    logDate: '15/10/2022',
    operadorName: 'Diego',
    operadorId: 2,
  },
  {
    showCode: 'C123456',
    title: 'COCA-COLA',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '01/10/2022',
    readyQc: '02/10/2022',
    readyQcValue: true,
    qcOk: '03/10/2022',
    qcOkId: 3,
    dalet: '',
    typeId: 1,
    typeName: 'COMERCIAL',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 953,
    logDate: '15/10/2022',
    operadorName: 'Maxi',
    operadorId: 3,
  },
  {
    showCode: 'ARFI01256',
    title: 'xxxx 2323',
    priorityId: 1,
    priorityName: 'High',
    placeH: '',
    readyQc: '',
    readyQcValue: false,
    qcOk: '',
    qcOkId: 2,
    dalet: '',
    typeId: 3,
    typeName: 'Long F.',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 178,
    logDate: '17/11/2022',
    operadorName: 'Jose',
    operadorId: 1,
  },
  {
    showCode: 'ARFI01354',
    title: 'xxxx 2324',
    priorityId: 1,
    priorityName: 'High',
    placeH: '18/10/2022',
    readyQc: '',
    readyQcValue: false,
    qcOk: '',
    qcOkId: 2,
    dalet: '',
    typeId: 2,
    typeName: 'PROMO',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 178,
    logDate: '18/11/2022',
    operadorName: 'Jose',
    operadorId: 1,
  },
  {
    showCode: 'ARFI02548',
    title: 'FI -GP EEUU0584',
    priorityId: 1,
    priorityName: 'High',
    placeH: '18/11/2022',
    readyQc: '',
    readyQcValue: false,
    qcOk: '',
    qcOkId: 2,
    dalet: '',
    typeId: 1,
    typeName: 'COMERCIAL',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 14,
    logDate: '18/11/2022',
    operadorName: 'Diego',
    operadorId: 2,
  },
  {
    showCode: 'ARFI04324',
    title: 'FI -GP EEUU3244',
    priorityId: 1,
    priorityName: 'High',
    placeH: '18/11/2022',
    readyQc: '',
    readyQcValue: false,
    qcOk: '',
    qcOkId: 2,
    dalet: '',
    typeId: 1,
    typeName: 'COMERCIAL',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 178,
    logDate: '18/11/2022',
    operadorName: 'Maxi',
    operadorId: 3,
  },
  {
    showCode: 'GRF2453',
    title: 'FI -S2224 EEUU',
    priorityId: 1,
    priorityName: 'High',
    placeH: '18/11/2022',
    readyQc: '',
    readyQcValue: false,
    qcOk: '',
    qcOkId: 2,
    dalet: '',
    typeId: 2,
    typeName: 'PROMO',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 954,
    logDate: '18/11/2022',
    operadorName: 'Ivan',
    operadorId: 4,
  },
  {
    showCode: 'G3452',
    title: 'FI -GP 3ED C',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '19/11/2022',
    readyQc: '20/11/2022',
    readyQcValue: true,
    qcOk: '',
    qcOkId: 2,
    dalet: '',
    typeId: 3,
    typeName: 'Long F.',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 14,
    logDate: '19/11/2022',
    operadorName: 'Jose',
    operadorId: 1,
  },
  {
    showCode: 'G33452',
    title: 'FI -GP 2344',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '20/11/2022',
    readyQc: '21/11/2022',
    readyQcValue: true,
    qcOk: '',
    qcOkId: 2,
    dalet: '',
    typeId: 2,
    typeName: 'PROMO',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 953,
    logDate: '20/11/2022',
    operadorName: 'Diego',
    operadorId: 2,
  },
  {
    showCode: 'h33452',
    title: 'FI -GP 33552',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '21/11/2022',
    readyQc: '22/11/2022',
    readyQcValue: true,
    qcOk: '',
    qcOkId: 2,
    dalet: '',
    typeId: 1,
    typeName: 'COMERCIAL',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 178,
    logDate: '21/11/2022',
    operadorName: 'Maxi',
    operadorId: 3,
  },
  {
    showCode: 'GHH33452',
    title: 'FI -GP 3553221',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '22/11/2022',
    readyQc: '23/11/2022',
    readyQcValue: true,
    qcOk: '22/11/2022',
    qcOkId: 3,
    dalet: '',
    typeId: 3,
    typeName: 'Long F.',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 14,
    logDate: '22/11/2022',
    operadorName: 'Ivan',
    operadorId: 4,
  },
  {
    showCode: 'DFFE3322',
    title: 'FI -GP S224',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '23/11/2022',
    readyQc: '24/11/2022',
    readyQcValue: true,
    qcOk: 'Rejected',
    qcOkId: 1,
    dalet: '',
    typeId: 2,
    typeName: 'PROMO',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 958,
    logDate: '23/11/2022',
    operadorName: 'Jose',
    operadorId: 1,
  },
  {
    showCode: 'J3345',
    title: '3RVEUU',
    priorityId: 3,
    priorityName: 'Low',
    placeH: '5/12/2022',
    readyQc: '6/12/2022',
    readyQcValue: true,
    qcOk: '7/12/2022',
    qcOkId: 3,
    dalet: '',
    typeId: 3,
    typeName: 'Long F.',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 14,
    logDate: '05/12/2022',
    operadorName: 'Diego',
    operadorId: 2,
  },
  {
    showCode: 'h33224',
    title: 'FI 33255',
    priorityId: 3,
    priorityName: 'Low',
    placeH: '6/12/2022',
    readyQc: '',
    readyQcValue: false,
    qcOk: '',
    qcOkId: 2,
    dalet: '',
    typeId: 1,
    typeName: 'COMERCIAL',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 658,
    logDate: '05/10/2022',
    operadorName: 'Maxi',
    operadorId: 3,
  },
  {
    showCode: 'ffrrew3',
    title: '325UU',
    priorityId: 3,
    priorityName: 'Low',
    placeH: '08/12/2022',
    readyQc: '09/12/2022',
    readyQcValue: true,
    qcOk: 'Rejected',
    qcOkId: 1,
    dalet: '',
    typeId: 3,
    typeName: 'Long F.',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 14,
    logDate: '08/12/2022',
    operadorName: 'Ivan',
    operadorId: 4,
  },
  {
    showCode: 'gg4224',
    title: 'FI 3452',
    priorityId: 3,
    priorityName: 'Low',
    placeH: '10/12/2022',
    readyQc: '13/12/2022',
    readyQcValue: true,
    qcOk: '',
    qcOkId: 2,
    dalet: '',
    typeId: 2,
    typeName: 'PROMO',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 14,
    logDate: '10/12/2022',
    operadorName: 'Jose',
    operadorId: 1,
  },
  {
    showCode: 'YY2345',
    title: 'FI TYY24',
    priorityId: 3,
    priorityName: 'Low',
    placeH: '14/12/2022',
    readyQc: '14/12/2022',
    readyQcValue: true,
    qcOk: '15/12/2022',
    qcOkId: 3,
    dalet: '',
    typeId: 1,
    typeName: 'COMERCIAL',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 963,
    logDate: '14/12/2022',
    operadorName: 'Diego',
    operadorId: 2,
  },
  {
    showCode: 'wee2512',
    title: 'FI 21rw2',
    priorityId: 3,
    priorityName: 'Low',
    placeH: '15/12/2022',
    readyQc: '',
    readyQcValue: false,
    qcOk: 'Rejected',
    qcOkId: 1,
    dalet: '',
    typeId: 2,
    typeName: 'PROMO',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 178,
    logDate: '10/12/2022',
    operadorName: 'Maxi',
    operadorId: 3,
  },
  {
    showCode: 'yiwq12345',
    title: 'Feta12',
    priorityId: 3,
    priorityName: 'Low',
    placeH: '16/12/2022',
    readyQc: '17/12/2022',
    readyQcValue: true,
    qcOk: '18/12/2022',
    qcOkId: 3,
    dalet: '',
    typeId: 1,
    typeName: 'COMERCIAL',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 963,
    logDate: '16/12/2022',
    operadorName: 'Ivan',
    operadorId: 4,
  },
  {
    showCode: 'vvf1234',
    title: '3rr412',
    priorityId: 3,
    priorityName: 'Low',
    placeH: '20/12/2022',
    readyQc: '21/12/2022',
    readyQcValue: true,
    qcOk: 'Rejected',
    qcOkId: 1,
    dalet: '',
    typeId: 3,
    typeName: 'Long F.',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 178,
    logDate: '20/12/2022',
    operadorName: 'Jose',
    operadorId: 1,
  },
  {
    showCode: 'ooi12492',
    title: 'FS12442',
    priorityId: 3,
    priorityName: 'Low',
    placeH: '29/12/2022',
    readyQc: '30/12/2022',
    readyQcValue: true,
    qcOk: '31/12/2022',
    qcOkId: 3,
    dalet: '',
    typeId: 1,
    typeName: 'COMERCIAL',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 14,
    logDate: '29/12/2022',
    operadorName: 'Diego',
    operadorId: 2,
  },
  {
    showCode: 'E12341',
    title: '224FT344',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '20/11/2022',
    readyQc: '21/11/2022',
    readyQcValue: true,
    qcOk: '',
    qcOkId: 2,
    dalet: '',
    typeId: 3,
    typeName: 'Long F.',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 964,
    logDate: '20/11/2022',
    operadorName: 'Maxi',
    operadorId: 3,
  },
  {
    showCode: 'EW2345',
    title: '314GGE344',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '20/11/2022',
    readyQc: '21/11/2022',
    readyQcValue: true,
    qcOk: '22/11/2022',
    qcOkId: 3,
    dalet: '',
    typeId: 1,
    typeName: 'COMERCIAL',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 178,
    logDate: '20/11/2022',
    operadorName: 'Ivan',
    operadorId: 4,
  },
  {
    showCode: 'opfkdj3323',
    title: 'oi4234',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '20/11/2022',
    readyQc: '21/11/2022',
    readyQcValue: true,
    qcOk: '',
    qcOkId: 2,
    dalet: '',
    typeId: 2,
    typeName: 'PROMO',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 14,
    logDate: '20/11/2022',
    operadorName: 'Jose',
    operadorId: 1,
  },
  {
    showCode: 'TTQQ2234',
    title: 'F211224',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '20/11/2022',
    readyQc: '21/11/2022',
    readyQcValue: true,
    qcOk: 'Rejected',
    qcOkId: 1,
    dalet: '',
    typeId: 1,
    typeName: 'COMERCIAL',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 953,
    logDate: '20/11/2022',
    operadorName: 'Maxi',
    operadorId: 3,
  },
];

export const recordsData = [
  {
    showCode: 'ARFI01154',
    title: 'FI -GP EEUU',
    priorityId: 1,
    priorityName: 'High',
    placeH: '01/10/2022',
    forma:'VIVO',
    readyQcValue: false,
qcOk:"DONE",
    qcOkId: 2,
    dalet: '',
    typeId: 3,
    typeName: 'Long F.',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 178,
    recDate: '05/10/2022',
    operadorName: 'Jose',
    operadorId: 1,
    fo:'INP11'
  },
  {
    showCode: 'P123456',
    title: 'PROMO-XXXX',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '01/10/2022',
    forma:'DIFERIDO',
    readyQcValue: true,
qcOk:"DONE",
    qcOkId: 1,
    dalet: '',
    typeId: 2,
    typeName: 'PROMO',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 14,
    recDate: '15/10/2022',
    operadorName: 'Diego',
    operadorId: 2,
    fo:'INP22'
  },
  {
    showCode: 'C123456',
    title: 'COCA-COLA',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '01/10/2022',
    forma:'DIFERIDO',
    readyQcValue: true,
qcOk:"DONE",
    qcOkId: 3,
    dalet: '',
    typeId: 1,
    typeName: 'COMERCIAL',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 953,
    recDate: '15/10/2022',
    operadorName: 'Maxi',
    operadorId: 3,
    fo:'INP43'
  },
  {
    showCode: 'ARFI01256',
    title: 'xxxx 2323',
    priorityId: 1,
    priorityName: 'High',
    placeH: '',
    forma:'DIFERIDO',
    readyQcValue: false,
qcOk:"DONE",
    qcOkId: 2,
    dalet: '',
    typeId: 3,
    typeName: 'Long F.',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 178,
    recDate: '17/11/2022',
    operadorName: 'Jose',
    operadorId: 1,
    fo:'INP43'
  },
  {
    showCode: 'ARFI01354',
    title: 'xxxx 2324',
    priorityId: 1,
    priorityName: 'High',
    placeH: '18/10/2022',
    forma:'VIVO',
    readyQcValue: false,
qcOk:"DONE",
    qcOkId: 2,
    dalet: '',
    typeId: 2,
    typeName: 'PROMO',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 178,
    recDate: '18/11/2022',
    operadorName: 'Jose',
    operadorId: 1,
    fo:'INP11'
  },
  {
    showCode: 'ARFI02548',
    title: 'FI -GP EEUU0584',
    priorityId: 1,
    priorityName: 'High',
    placeH: '18/11/2022',
    forma:'VIVO',
    readyQcValue: false,
qcOk:"INPROGRESS",
    qcOkId: 2,
    dalet: '',
    typeId: 1,
    typeName: 'COMERCIAL',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 14,
    recDate: '18/11/2022',
    operadorName: 'Diego',
    operadorId: 2,
    fo:'INP11'
  },
  {
    showCode: 'ARFI04324',
    title: 'FI -GP EEUU3244',
    priorityId: 1,
    priorityName: 'High',
    placeH: '18/11/2022',
    forma:'VIVO',
    readyQcValue: false,
qcOk:"INPROGRESS",
    qcOkId: 2,
    dalet: '',
    typeId: 1,
    typeName: 'COMERCIAL',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 178,
    recDate: '18/11/2022',
    operadorName: 'Maxi',
    operadorId: 3,
    fo:'TDB'
  },
  {
    showCode: 'GRF2453',
    title: 'FI -S2224 EEUU',
    priorityId: 1,
    priorityName: 'High',
    placeH: '18/11/2022',
    forma:'VIVO',
    readyQcValue: false,
qcOk:"INPROGRESS",
    qcOkId: 2,
    dalet: '',
    typeId: 2,
    typeName: 'PROMO',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 954,
    recDate: '18/11/2022',
    operadorName: 'Ivan',
    operadorId: 4,
    fo:'TDB'
  },
  {
    showCode: 'G3452',
    title: 'FI -GP 3ED C',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '19/11/2022',
    forma:'VIVO',
    readyQcValue: true,
qcOk:"INPROGRESS",
    qcOkId: 2,
    dalet: '',
    typeId: 3,
    typeName: 'Long F.',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 14,
    recDate: '19/11/2022',
    operadorName: 'Jose',
    operadorId: 1,
    fo:'INP11'
  },
  {
    showCode: 'G33452',
    title: 'FI -GP 2344',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '20/11/2022',
    forma:'VIVO',
    readyQcValue: true,
qcOk:"INPROGRESS",
    qcOkId: 2,
    dalet: '',
    typeId: 2,
    typeName: 'PROMO',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 953,
    recDate: '20/11/2022',
    operadorName: 'Diego',
    operadorId: 2,
    fo:'INP11'
  },
  {
    showCode: 'h33452',
    title: 'FI -GP 33552',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '21/11/2022',
    forma:'VIVO',
    readyQcValue: true,
qcOk:"DONE",
    qcOkId: 2,
    dalet: '',
    typeId: 1,
    typeName: 'COMERCIAL',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 178,
    recDate: '21/11/2022',
    operadorName: 'Maxi',
    operadorId: 3,
    fo:'TDB'
  },
  {
    showCode: 'GHH33452',
    title: 'FI -GP 3553221',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '22/11/2022',
    forma:'VIVO',
    readyQcValue: true,
qcOk:"DONE",
    qcOkId: 3,
    dalet: '',
    typeId: 3,
    typeName: 'Long F.',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 14,
    recDate: '22/11/2022',
    operadorName: 'Ivan',
    operadorId: 4,
    fo:'TDB'
  },
  {
    showCode: 'DFFE3322',
    title: 'FI -GP S224',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '23/11/2022',
    forma:'VIVO',
    readyQcValue: true,
qcOk:"DONE",
    qcOkId: 1,
    dalet: '',
    typeId: 2,
    typeName: 'PROMO',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 958,
    recDate: '23/11/2022',
    operadorName: 'Jose',
    operadorId: 1,
    fo:'TDB'
  },
  {
    showCode: 'J3345',
    title: '3RVEUU',
    priorityId: 3,
    priorityName: 'Low',
    placeH: '5/12/2022',
    forma:'VIVO',
    readyQcValue: true,
qcOk:"DONE",
    qcOkId: 3,
    dalet: '',
    typeId: 3,
    typeName: 'Long F.',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 14,
    recDate: '05/12/2022',
    operadorName: 'Diego',
    operadorId: 2,
    fo:'INP11'
  },
  {
    showCode: 'h33224',
    title: 'FI 33255',
    priorityId: 3,
    priorityName: 'Low',
    placeH: '6/12/2022',
    forma:'VIVO',
    readyQcValue: false,
qcOk:"DONE",
    qcOkId: 2,
    dalet: '',
    typeId: 1,
    typeName: 'COMERCIAL',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 658,
    recDate: '05/10/2022',
    operadorName: 'Maxi',
    operadorId: 3,
    fo:'INP11'
  },
  {
    showCode: 'ffrrew3',
    title: '325UU',
    priorityId: 3,
    priorityName: 'Low',
    placeH: '08/12/2022',
    forma:'VIVO',
    readyQcValue: true,
qcOk:"DONE",
    qcOkId: 1,
    dalet: '',
    typeId: 3,
    typeName: 'Long F.',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 14,
    recDate: '08/12/2022',
    operadorName: 'Ivan',
    operadorId: 4,
    fo:'INP11'
  },
  {
    showCode: 'gg4224',
    title: 'FI 3452',
    priorityId: 3,
    priorityName: 'Low',
    placeH: '10/12/2022',
    forma:'VIVO',
    readyQcValue: true,
qcOk:"DONE",
    qcOkId: 2,
    dalet: '',
    typeId: 2,
    typeName: 'PROMO',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 14,
    recDate: '10/12/2022',
    operadorName: 'Jose',
    operadorId: 1,
    fo:'INP11'
  },
  {
    showCode: 'YY2345',
    title: 'FI TYY24',
    priorityId: 3,
    priorityName: 'Low',
    placeH: '14/12/2022',
    forma:'VIVO',
    readyQcValue: true,
qcOk:"DONE",
    qcOkId: 3,
    dalet: '',
    typeId: 1,
    typeName: 'COMERCIAL',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 963,
    recDate: '14/12/2022',
    operadorName: 'Diego',
    operadorId: 2,
    fo:'INP11'
  },
  {
    showCode: 'wee2512',
    title: 'FI 21rw2',
    priorityId: 3,
    priorityName: 'Low',
    placeH: '15/12/2022',
    forma:'VIVO',
    readyQcValue: false,
qcOk:"WARNING",
    qcOkId: 1,
    dalet: '',
    typeId: 2,
    typeName: 'PROMO',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 178,
    recDate: '10/12/2022',
    operadorName: 'Maxi',
    operadorId: 3,
    fo:'INP11'
  },
  {
    showCode: 'yiwq12345',
    title: 'Feta12',
    priorityId: 3,
    priorityName: 'Low',
    placeH: '16/12/2022',
    forma:'VIVO',
    readyQcValue: true,
qcOk:"WARNING",
    qcOkId: 3,
    dalet: '',
    typeId: 1,
    typeName: 'COMERCIAL',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 963,
    recDate: '16/12/2022',
    operadorName: 'Ivan',
    operadorId: 4,
    fo:'INP11'
  },
  {
    showCode: 'vvf1234',
    title: '3rr412',
    priorityId: 3,
    priorityName: 'Low',
    placeH: '20/12/2022',
    forma:'DIFERIDO',
    readyQcValue: true,
qcOk:"WARNING",
    qcOkId: 1,
    dalet: '',
    typeId: 3,
    typeName: 'Long F.',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 178,
    recDate: '20/12/2022',
    operadorName: 'Jose',
    operadorId: 1,
    fo:'INP11'
  },
  {
    showCode: 'ooi12492',
    title: 'FS12442',
    priorityId: 3,
    priorityName: 'Low',
    placeH: '29/12/2022',
    forma:'DIFERIDO',
    readyQcValue: true,
qcOk:"WARNING",
    qcOkId: 3,
    dalet: '',
    typeId: 1,
    typeName: 'COMERCIAL',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 14,
    recDate: '29/12/2022',
    operadorName: 'Diego',
    operadorId: 2,
    fo:'INP11'
  },
  {
    showCode: 'E12341',
    title: '224FT344',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '20/11/2022',
    forma:'DIFERIDO',
    readyQcValue: true,
qcOk:"WARNING",
    qcOkId: 2,
    dalet: '',
    typeId: 3,
    typeName: 'Long F.',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 964,
    recDate: '20/11/2022',
    operadorName: 'Maxi',
    operadorId: 3,
    fo:'INP11'
  },
  {
    showCode: 'EW2345',
    title: '314GGE344',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '20/11/2022',
    forma:'DIFERIDO',
    readyQcValue: true,
qcOk:"WARNING",
    qcOkId: 3,
    dalet: '',
    typeId: 1,
    typeName: 'COMERCIAL',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 178,
    recDate: '20/11/2022',
    operadorName: 'Ivan',
    operadorId: 4,
    fo:'INP11'
  },
  {
    showCode: 'opfkdj3323',
    title: 'oi4234',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '20/11/2022',
    forma:'VIVO',
    readyQcValue: true,
qcOk:"WARNING",
    qcOkId: 2,
    dalet: '',
    typeId: 2,
    typeName: 'PROMO',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 14,
    recDate: '20/11/2022',
    operadorName: 'Jose',
    operadorId: 1,
    fo:'INP11'
  },
  {
    showCode: 'TTQQ2234',
    title: 'F211224',
    priorityId: 2,
    priorityName: 'Medium',
    placeH: '20/11/2022',
    forma:'VIVO',
    readyQcValue: true,
qcOk:"WARNING",
    qcOkId: 1,
    dalet: '',
    typeId: 1,
    typeName: 'COMERCIAL',
    edm: '',
    tmk: '',
    inetsat: '',
    feed: 953,
    recDate: '20/11/2022',
    operadorName: 'Maxi',
    operadorId: 3,
    fo:'INP11'
  },
];
